# version: '3.8' # <-- Удалите эту строку

services:
  # Сервис для Django-приложения
  web:
    build: . # Собираем из Dockerfile в текущей директории
    ports:
      - "8000:8000" # Пробрасываем порт 8000 с хоста на порт 8000 в контейнере
    volumes:
      # Синхронизируем исходный код между хостом и контейнером
      # Это позволяет видеть изменения в коде без пересборки контейнера
      - .:/app
      # Монтируем директории для медиа-файлов и статики, чтобы они сохранялись на хосте
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
